#!/usr/bin/env bash
# 10-download-artifact.sh
#
# Downloads the patch artifact generated by pr-to-internal.yml CI workflow.
# The artifact contains pr.patch and pr-meta.json needed by apply-external-pr.sh.
#
# Usage:
#   ./test/10-download-artifact.sh --party acme --pr 1
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEST_CONF="${SCRIPT_DIR}/test.conf"

[[ -f "$TEST_CONF" ]] || { echo "test.conf not found."; exit 1; }
source "$TEST_CONF"

SYNC_CONF="${REPO_ROOT}/config/sync.conf"
[[ -f "$SYNC_CONF" ]] || { echo "config/sync.conf not found."; exit 1; }
source "$SYNC_CONF"

log() { echo -e "\033[1;34m[artifact]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[   ok  ]\033[0m $*"; }
die() { echo -e "\033[1;31m[  err  ]\033[0m $*" >&2; exit 1; }

PARTY=""
PR_NUMBER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --party) PARTY="$2";     shift 2 ;;
    --pr)    PR_NUMBER="$2"; shift 2 ;;
    *) die "Unknown option: $1\nUsage: $0 --party <name> --pr <number>" ;;
  esac
done

[[ -n "$PARTY"     ]] || die "Specify --party <name>"
[[ -n "$PR_NUMBER" ]] || die "Specify --pr <pr-number>"

PARTY_CONF="${REPO_ROOT}/config/party/${PARTY}.conf"
[[ -f "$PARTY_CONF" ]] || die "Party config not found: ${PARTY_CONF}"
source "$PARTY_CONF"

OUTPUT_DIR="${REPO_ROOT}/test-artifacts/${PARTY}/pr-${PR_NUMBER}"
mkdir -p "$OUTPUT_DIR"

# ── Find the latest CI run for this PR ────────────────────────
log "Looking for CI run for PR #${PR_NUMBER} on ${REPLICA_GH_REPO}..."

# Get the current head SHA of the PR to identify the correct run
HEAD_SHA=$(gh pr view "$PR_NUMBER" \
  --repo "$REPLICA_GH_REPO" \
  --json headRefOid --jq '.headRefOid')

[[ -n "$HEAD_SHA" ]] || die "Could not get head SHA for PR #${PR_NUMBER}"
log "PR head SHA: ${HEAD_SHA:0:8}"

# Find the completed successful run triggered by this PR's head SHA
RUN_ID=$(gh run list \
  --repo "$REPLICA_GH_REPO" \
  --workflow "pr-to-internal.yml" \
  --json databaseId,status,conclusion,headSha \
  --jq ".[] | select(.headSha == \"$HEAD_SHA\" and .status == \"completed\" and .conclusion == \"success\") | .databaseId" \
  | head -1)

if [[ -z "$RUN_ID" ]]; then
  ALL_RUNS=$(gh run list \
    --repo "$REPLICA_GH_REPO" \
    --workflow "pr-to-internal.yml" \
    --json databaseId,status,conclusion,headSha \
    --jq ".[] | select(.headSha == \"$HEAD_SHA\") | \"\(.databaseId)  status=\(.status)  conclusion=\(.conclusion)\"" \
    | head -5)

  if [[ -z "$ALL_RUNS" ]]; then
    die "No CI runs found for PR #${PR_NUMBER} (head: ${HEAD_SHA:0:8}).\n" \
        "Make sure the workflow has run:\n" \
        "  gh run list --repo ${REPLICA_GH_REPO} --workflow pr-to-internal.yml"
  else
    echo "Runs for this PR head:"
    echo "$ALL_RUNS"
    die "No completed successful run found. Wait for CI to finish."
  fi
fi

log "Found run: ${RUN_ID}"

# ── Download artifact ─────────────────────────────────────────
ARTIFACT_NAME="pr-${PR_NUMBER}-"
log "Downloading artifact for PR #${PR_NUMBER}..."

cd "$OUTPUT_DIR"
gh run download "$RUN_ID" \
  --repo "$REPLICA_GH_REPO" \
  --dir "$OUTPUT_DIR" \
  --pattern "pr-${PR_NUMBER}-*" \
  2>/dev/null || {
  # If pattern match fails, download all artifacts from the run
  log "Pattern match failed, downloading all artifacts from run ${RUN_ID}..."
  gh run download "$RUN_ID" \
    --repo "$REPLICA_GH_REPO" \
    --dir "$OUTPUT_DIR"
}

# Flatten nested directories if artifact was downloaded into subdirectory
PATCH_FILE=$(find "$OUTPUT_DIR" -name "pr.patch" | head -1)
META_FILE=$(find "$OUTPUT_DIR" -name "pr-meta.json" | head -1)

[[ -f "$PATCH_FILE" ]] || die "pr.patch not found in downloaded artifact"
[[ -f "$META_FILE"  ]] || die "pr-meta.json not found in downloaded artifact"

# Move to output dir root if in subdirectory
[[ "$(dirname "$PATCH_FILE")" != "$OUTPUT_DIR" ]] && cp "$PATCH_FILE" "$OUTPUT_DIR/pr.patch"
[[ "$(dirname "$META_FILE")"  != "$OUTPUT_DIR" ]] && cp "$META_FILE"  "$OUTPUT_DIR/pr-meta.json"

PATCH_FILE="${OUTPUT_DIR}/pr.patch"
META_FILE="${OUTPUT_DIR}/pr-meta.json"

PR_TITLE=$(jq -r '.pr_title' "$META_FILE")
PR_AUTHOR=$(jq -r '.pr_author' "$META_FILE")

ok "Artifact downloaded:"
ok "  patch    : ${PATCH_FILE}"
ok "  meta     : ${META_FILE}"
ok "  PR title : ${PR_TITLE}"
ok "  PR author: ${PR_AUTHOR}"
echo ""
echo "Next: apply the patch to the internal repo"
echo "  ./scripts/apply-external-pr.sh \\"
echo "    --patch ${PATCH_FILE} \\"
echo "    --meta  ${META_FILE}"
