#!/usr/bin/env bash
# deliver-to-replica.sh
#
# Milestone sync - Phase 2.
# Delivers the publish branch content to the external replica for the given party.
# Run after: init-replica.sh or stage-publish.sh -> GHE PR review -> merge.
#
# On first delivery (no last-sync tag yet), delivers from the beginning of the
# publish branch and also sets the replica/<party>/init-TIMESTAMP tag.
#
# Usage:
#   # Output patch set (default; 3rd party opens a PR)
#   ./scripts/deliver-to-replica.sh --party acme "sync: 2024-Q1"
#
#   # Output patch set (3rd party applies directly to main)
#   ./scripts/deliver-to-replica.sh --party acme --mode direct "sync: 2024-Q1"
#
#   # Re-generate patch without advancing sync tags (e.g. to resend lost files)
#   ./scripts/deliver-to-replica.sh --party acme --resend "sync: 2024-Q1"
#
#   # Push as a PR to the replica
#   ./scripts/deliver-to-replica.sh --party acme --output push "sync: 2024-Q1"
#
#   # Push directly to main on the replica
#   ./scripts/deliver-to-replica.sh --party acme --output push --mode direct "sync: 2024-Q1"
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/../config/sync.conf"

[[ -f "$CONFIG_FILE" ]] || {
  echo "Config file not found: $CONFIG_FILE"
  exit 1
}
# shellcheck source=../config/sync.conf.example
source "$CONFIG_FILE"

# Defaults for optional config values (prevents -u errors when unset)
: "${PATCH_OUTPUT_DIR:=./sync-patches}"

log() { echo -e "\033[1;34m[deliver]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[  ok   ]\033[0m $*"; }
die() { echo -e "\033[1;31m[ err   ]\033[0m $*" >&2; exit 1; }

# ── Argument parsing ───────────────────────────────────────────
OUTPUT_MODE="patch"  # push | patch
MODE="pr"            # pr | direct
PARTY=""
COMMIT_MSG=""
RESEND="false"       # true = regenerate patch without advancing sync tags

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT_MODE="$2"; shift 2 ;;
    --mode)   MODE="$2";        shift 2 ;;
    --party)  PARTY="$2";       shift 2 ;;
    --resend) RESEND="true";    shift ;;
    --*)      die "Unknown option: $1" ;;
    *)        COMMIT_MSG="$1"; shift ;;
  esac
done

[[ -n "$PARTY" ]] || die "Specify a party name with --party\n  Example: $0 --party acme \"sync: 2024-Q1\""
COMMIT_MSG="${COMMIT_MSG:-"sync: $(date +%Y-%m-%d)"}"

case "$OUTPUT_MODE" in
  push|patch) ;;
  *) die "--output must be push or patch" ;;
esac

case "$MODE" in
  pr|direct) ;;
  *) die "--mode must be pr or direct" ;;
esac

# Load per-party config (provides REPLICA_REPO, REPLICA_REMOTE, REPLICA_BRANCH, REPLICA_GH_REPO)
PARTY_CONFIG="${SCRIPT_DIR}/../config/party/${PARTY}.conf"
[[ -f "$PARTY_CONFIG" ]] || die "Party config not found: $PARTY_CONFIG\n  Run: cp config/party/party.conf.example config/party/${PARTY}.conf and edit it"
# shellcheck source=../config/party/party.conf.example
source "$PARTY_CONFIG"

PUBLISH_BRANCH="publish"
PARTY_SYNC_TAG="replica/${PARTY}/last-sync"

BOOTSTRAP_COMMON_DIR="${SCRIPT_DIR}/../config/replica-bootstrap"
BOOTSTRAP_PARTY_DIR="${BOOTSTRAP_COMMON_DIR}/${PARTY}"

log "Party         : $PARTY"
log "Output mode   : $OUTPUT_MODE"
log "Apply mode    : $MODE"
log "Commit message: $COMMIT_MSG"

# ── Helpers ────────────────────────────────────────────────────

# Copy bootstrap files to a destination directory.
# Applies common files first (skipping the party-named subdir), then party-specific.
copy_bootstrap() {
  local dest="$1"
  if [[ -d "$BOOTSTRAP_COMMON_DIR" ]]; then
    # find handles hidden dirs like .github/ that shell globs skip
    find "$BOOTSTRAP_COMMON_DIR" -maxdepth 1 -mindepth 1 ! -name "$PARTY" \
      -exec cp -r {} "${dest}/" \;
    log "Bootstrap: common files applied"
  fi
  if [[ -d "$BOOTSTRAP_PARTY_DIR" ]]; then
    cp -r "${BOOTSTRAP_PARTY_DIR}/." "${dest}/"
    log "Bootstrap: party-specific files applied (${PARTY})"
  fi
}

# List publish commits since last-sync for this party
generate_deliver_summary() {
  cd "$INTERNAL_REPO"
  git log --oneline --no-merges "${LAST_SYNC_SHA}..${PUBLISH_HEAD}" \
    | head -50
}

generate_pr_body() {
  cat << EOF
## ${COMMIT_MSG}

| Field    | Value |
|----------|-------|
| Range    | \`${LAST_SYNC_SHA:0:8}\`..\`${PUBLISH_HEAD:0:8}\` |
| Delivered| $(date '+%Y-%m-%d %H:%M:%S') |

## Change summary

\`\`\`
$(generate_deliver_summary)
\`\`\`

> This PR was auto-generated by the internal sync bot.
> Please review and merge.
EOF
}

# Generate README.md — human-readable guide included in the patch zip
generate_readme() {
  local output_file="$1"
  local ts="$TIMESTAMP"
  local msg="$COMMIT_MSG"
  local default_mode="$MODE"
  local first="$FIRST_DELIVERY"
  local last_short="${LAST_SYNC_SHA:0:8}"
  local head_short="${PUBLISH_HEAD:0:8}"

  cat > "$output_file" << README
# Sync Package — ${msg}

This package contains an upstream sync from the internal repository.
Apply it to your local clone of the replica repository.

## Package contents

| File | Description |
|---|---|
| \`sync-${ts}.patch\` | Git diff patch (upstream changes) |
| \`sync-${ts}-meta.json\` | Metadata (commit range, PR title, delivery info) |
| \`sync-${ts}-summary.txt\` | List of upstream commits included in this sync |
| \`sync-${ts}-apply.sh\` | Apply script — run this to apply the patch |
$([ "$first" = "true" ] && echo "| \`sync-${ts}-bootstrap/\` | Bootstrap files added on first delivery |")

## Delivery info

| Field | Value |
|---|---|
| Sync message | \`${msg}\` |
| Delivered at | $(date '+%Y-%m-%d %H:%M:%S') |
| Commit range | \`${last_short}\`..\`${head_short}\` |
| Default apply mode | \`${default_mode}\` |

## How to apply

**Prerequisites:** \`git\`, \`jq\`, and \`gh\` (gh CLI required only for PR mode).

**Step 1 — Extract this package** (if not already done):

\`\`\`bash
unzip sync-${ts}-*.zip
cd sync-${ts}-*/
\`\`\`

**Step 2 — Run the apply script** from your local clone of the replica:

\`\`\`bash
# Run from the root of the replica (any branch is fine — the script switches to main automatically)
cd /path/to/replica
bash /path/to/sync-${ts}-apply.sh
\`\`\`

Or specify the mode explicitly:

\`\`\`bash
bash sync-${ts}-apply.sh --mode pr      # push sync branch and open a PR (recommended)
bash sync-${ts}-apply.sh --mode direct  # apply directly to main
\`\`\`

**Step 3 — Review and merge** (PR mode only):

After running the script, a PR titled \`${msg}\` will be opened on the repository.
Review the changes and merge it to update \`main\`.

**Step 4 — Rebase your development branches:**

\`\`\`bash
git checkout your-feature-branch
git rebase main
\`\`\`

## Change summary

\`\`\`
$(generate_deliver_summary)
\`\`\`
README
}

# Generate apply.sh — a standalone script for the 3rd party to apply the patch
generate_apply_sh() {
  local output_file="$1"
  local ts="$TIMESTAMP"
  local msg="$COMMIT_MSG"
  local default_mode="$MODE"
  local script_name="sync-${ts}-apply.sh"

  sed \
    -e "s|%%TIMESTAMP%%|${ts}|g" \
    -e "s|%%COMMIT_MSG%%|${msg}|g" \
    -e "s|%%DEFAULT_MODE%%|${default_mode}|g" \
    -e "s|%%SCRIPT_NAME%%|${script_name}|g" \
    << 'APPLY_TEMPLATE' > "$output_file"
#!/usr/bin/env bash
# Sync apply script (generated: %%TIMESTAMP%%)
# Sync message: %%COMMIT_MSG%%
#
# Usage:
#   # Apply with the default mode (%%DEFAULT_MODE%%)
#   ./%%SCRIPT_NAME%%
#
#   # Specify a mode explicitly
#   ./%%SCRIPT_NAME%% --mode pr      # push sync branch and open a PR
#   ./%%SCRIPT_NAME%% --mode direct  # apply directly to main
#
# Prerequisites:
#   - Run from the root of the replica repository
#   - The script switches to main automatically before branching; no need to
#     switch branches manually beforehand
#   - jq must be installed; gh CLI is required only for pr mode
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PATCH_FILE="${SCRIPT_DIR}/sync-%%TIMESTAMP%%.patch"
META_FILE="${SCRIPT_DIR}/sync-%%TIMESTAMP%%-meta.json"
BOOTSTRAP_DIR="${SCRIPT_DIR}/sync-%%TIMESTAMP%%-bootstrap"
SYNC_BRANCH="sync/%%TIMESTAMP%%"
REPLICA_BRANCH="main"
DEFAULT_MODE="%%DEFAULT_MODE%%"

log() { echo -e "\033[1;34m[apply]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[  ok  ]\033[0m $*"; }
die() { echo -e "\033[1;31m[ err  ]\033[0m $*" >&2; exit 1; }

MODE="${DEFAULT_MODE}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --*)    die "Unknown option: $1" ;;
    *) break ;;
  esac
done

[[ -f "$PATCH_FILE" ]] || die "Patch file not found: $PATCH_FILE"
[[ -f "$META_FILE"  ]] || die "Meta file not found: $META_FILE"
command -v jq >/dev/null 2>&1 || die "jq is not installed"
[[ "$MODE" == "pr" ]] && { command -v gh >/dev/null 2>&1 || die "gh CLI is not installed"; }

PR_TITLE=$(jq -r '.pr_title'       "$META_FILE")
PR_BODY=$(jq  -r '.pr_body'        "$META_FILE")
FIRST_DELIVERY=$(jq -r '.first_delivery' "$META_FILE")

log "Apply mode: $MODE"

apply_bootstrap() {
  if [[ "$FIRST_DELIVERY" == "true" && -d "$BOOTSTRAP_DIR" ]]; then
    log "Applying bootstrap files..."
    cp -r "${BOOTSTRAP_DIR}/." .
    ok "Bootstrap applied"
  fi
}

apply_patch() {
  if [[ "$FIRST_DELIVERY" == "true" ]]; then
    # First delivery: clear working tree before applying so existing files
    # (e.g. GitHub-initialized README) do not cause false conflicts.
    log "First delivery: clearing working tree before patch apply..."
    git rm -rf . --quiet
  fi
  log "Applying patch..."
  git apply --whitespace=nowarn "$PATCH_FILE" \
    || die "Patch apply failed. Resolve conflicts and re-run."
}

if [[ "$MODE" == "pr" ]]; then
  log "Switching to $REPLICA_BRANCH before branching..."
  git checkout "$REPLICA_BRANCH"
  log "Creating branch: $SYNC_BRANCH"
  git checkout -b "$SYNC_BRANCH"

  apply_patch
  apply_bootstrap

  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "$PR_TITLE"
    ok "Commit: $(git rev-parse --short HEAD)"
  else
    ok "No changes to commit."
  fi

  git push origin "$SYNC_BRANCH"

  gh pr create \
    --title "$PR_TITLE" \
    --body  "$PR_BODY"  \
    --base  "$REPLICA_BRANCH" \
    --head  "$SYNC_BRANCH"

  ok "PR created"

elif [[ "$MODE" == "direct" ]]; then
  log "Applying directly to main..."
  git checkout "$REPLICA_BRANCH"

  apply_patch
  apply_bootstrap

  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "$PR_TITLE"
    ok "Commit: $(git rev-parse --short HEAD)"
  else
    ok "No changes to commit."
  fi

  git push origin "$REPLICA_BRANCH"
  ok "Applied directly to main"

else
  die "--mode must be pr or direct"
fi
APPLY_TEMPLATE
  chmod +x "$output_file"
}

# ── Step 1: Pre-flight checks ─────────────────────────────────
cd "$INTERNAL_REPO"

# Fetch to ensure publish branch reflects latest remote state (e.g. after PR merge)
git fetch "$INTERNAL_REMOTE"

git rev-parse --verify "refs/remotes/${INTERNAL_REMOTE}/${PUBLISH_BRANCH}" >/dev/null 2>&1 \
  || die "Publish branch '$PUBLISH_BRANCH' not found on remote.\n" \
         "Run initial setup first:\n" \
         "  ./scripts/init-replica.sh <start-tag>"

PUBLISH_HEAD=$(git rev-parse "${INTERNAL_REMOTE}/${PUBLISH_BRANCH}")

# Determine delivery base: last-sync tag (subsequent) or publish root (first)
FIRST_DELIVERY=false
if git rev-parse --verify "$PARTY_SYNC_TAG" >/dev/null 2>&1; then
  LAST_SYNC_SHA=$(git rev-parse "$PARTY_SYNC_TAG")
else
  # First delivery: base is the empty root commit of the publish branch
  LAST_SYNC_SHA=$(git rev-list --max-parents=0 "${INTERNAL_REMOTE}/${PUBLISH_BRANCH}")
  FIRST_DELIVERY=true
  log "First delivery for party '${PARTY}' (no last-sync tag found)"
fi

if [[ "$PUBLISH_HEAD" == "$LAST_SYNC_SHA" ]]; then
  if [[ "$RESEND" != "true" ]]; then
    ok "Already delivered. No undelivered changes on publish branch."
    exit 0
  fi
  log "--resend: already delivered; will look back to previous sync base"
fi

log "Delivery range: ${LAST_SYNC_SHA:0:8}..${PUBLISH_HEAD:0:8}"

# ── Step 2: Generate diff patch ───────────────────────────────
# publish branch already has EXCLUDE_PATHS applied by init-replica.sh / stage-publish.sh
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PATCH_FILE=$(mktemp /tmp/deliver-XXXXXX.patch)
trap 'rm -f "$PATCH_FILE"' EXIT

git diff "${LAST_SYNC_SHA}..${PUBLISH_HEAD}" > "$PATCH_FILE"

if [[ ! -s "$PATCH_FILE" ]]; then
  if [[ "$RESEND" != "true" ]]; then
    ok "No diff. Skipping."
    exit 0
  fi

  # --resend: diff is empty (last-sync == publish HEAD).
  # Walk sync tags to find the commit just before the current last-sync,
  # then regenerate the patch from that point to PUBLISH_HEAD.
  log "--resend: no diff from current base; finding previous sync base..."
  CURRENT_SYNC_COMMIT=$(git rev-parse "${PARTY_SYNC_TAG}^{}" 2>/dev/null || echo "")
  PREV_BASE_SHA=""
  while IFS= read -r stag; do
    sha=$(git rev-parse "${stag}^{}" 2>/dev/null) || continue
    [[ "$sha" == "$CURRENT_SYNC_COMMIT" ]] && continue
    PREV_BASE_SHA="$sha"  # last value in sorted order before current
  done < <(git tag -l "replica/${PARTY}/sync-*" | sort)

  if [[ -n "$PREV_BASE_SHA" ]]; then
    log "--resend: regenerating from ${PREV_BASE_SHA:0:8}..${PUBLISH_HEAD:0:8}"
    LAST_SYNC_SHA="$PREV_BASE_SHA"
  else
    # Only one prior delivery — regenerate from publish root
    LAST_SYNC_SHA=$(git rev-list --max-parents=0 "${INTERNAL_REMOTE}/${PUBLISH_BRANCH}")
    log "--resend: only one prior sync; regenerating from publish root (${LAST_SYNC_SHA:0:8}..${PUBLISH_HEAD:0:8})"
  fi

  git diff "${LAST_SYNC_SHA}..${PUBLISH_HEAD}" > "$PATCH_FILE"

  if [[ ! -s "$PATCH_FILE" ]]; then
    ok "--resend: still no diff after base lookup. Nothing to regenerate."
    exit 0
  fi

  FIRST_DELIVERY=false  # resend is never treated as a first delivery
fi

log "Patch size: $(wc -l < "$PATCH_FILE") lines"

# ── patch mode: write files and exit ──────────────────────────
if [[ "$OUTPUT_MODE" == "patch" ]]; then
  PATCH_SET_NAME="sync-${TIMESTAMP}-${PARTY}"
  mkdir -p "$PATCH_OUTPUT_DIR"
  PATCH_OUTPUT_DIR="$(cd "$PATCH_OUTPUT_DIR" && pwd)"  # resolve to absolute path
  PATCH_SET_ZIP="${PATCH_OUTPUT_DIR}/${PATCH_SET_NAME}.zip"
  WORK_PATCH_DIR=$(mktemp -d /tmp/patch-set-XXXXXX)
  cleanup_patch() { rm -rf "$WORK_PATCH_DIR"; rm -f "$PATCH_FILE"; }
  trap cleanup_patch EXIT

  DEST_PATCH="${WORK_PATCH_DIR}/sync-${TIMESTAMP}.patch"
  DEST_META="${WORK_PATCH_DIR}/sync-${TIMESTAMP}-meta.json"
  DEST_SUMMARY="${WORK_PATCH_DIR}/sync-${TIMESTAMP}-summary.txt"
  DEST_APPLY="${WORK_PATCH_DIR}/sync-${TIMESTAMP}-apply.sh"
  DEST_README="${WORK_PATCH_DIR}/README.md"
  DEST_BOOTSTRAP="${WORK_PATCH_DIR}/sync-${TIMESTAMP}-bootstrap"

  cp "$PATCH_FILE" "$DEST_PATCH"

  PR_BODY_VAL="$(generate_pr_body)"

  cat > "$DEST_META" << EOF
{
  "commit_msg":     "${COMMIT_MSG}",
  "publish_head":   "${PUBLISH_HEAD}",
  "last_sync_sha":  "${LAST_SYNC_SHA}",
  "first_delivery": ${FIRST_DELIVERY},
  "timestamp":      "${TIMESTAMP}",
  "party":          "${PARTY}",
  "sync_branch":    "sync/${TIMESTAMP}",
  "pr_title":       "${COMMIT_MSG}",
  "pr_body":        $(echo "$PR_BODY_VAL" | jq -Rs .),
  "default_mode":   "${MODE}"
}
EOF

  generate_deliver_summary > "$DEST_SUMMARY"
  generate_apply_sh "$DEST_APPLY"
  generate_readme "$DEST_README"

  if [[ "$FIRST_DELIVERY" == "true" ]] && \
     { [[ -d "$BOOTSTRAP_COMMON_DIR" ]] || [[ -d "$BOOTSTRAP_PARTY_DIR" ]]; }; then
    mkdir -p "$DEST_BOOTSTRAP"
    copy_bootstrap "$DEST_BOOTSTRAP"
    ok "Bootstrap: files collected -> $DEST_BOOTSTRAP"
  fi

  # ── Create zip archive ──────────────────────────────────────
  (cd "$WORK_PATCH_DIR" && zip -r "$PATCH_SET_ZIP" . -x "*.DS_Store" >/dev/null)

  ok "Patch set created: ${PATCH_SET_ZIP}"
  echo "  README    : README.md"
  echo "  patch     : sync-${TIMESTAMP}.patch"
  echo "  meta      : sync-${TIMESTAMP}-meta.json"
  echo "  summary   : sync-${TIMESTAMP}-summary.txt"
  echo "  apply     : sync-${TIMESTAMP}-apply.sh"
  [[ -d "$DEST_BOOTSTRAP" ]] && echo "  bootstrap : sync-${TIMESTAMP}-bootstrap/"
  echo ""
  echo "Send this zip to the 3rd party:"
  echo "  ${PATCH_SET_ZIP}"
  echo ""
  echo "They can apply it by extracting and running:"
  echo "  unzip $(basename "$PATCH_SET_ZIP") && bash sync-${TIMESTAMP}-apply.sh"

  # ── Advance sync tags (patch mode) ───────────────────────────
  # Tags are advanced at patch generation time. The patch set is the
  # deliverable; whether the 3rd party has applied it is out of scope.
  # Skipped when --resend is specified (tags already reflect this delivery).
  if [[ "$RESEND" != "true" ]]; then
    SYNC_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
    TAG_MESSAGE="party: ${PARTY}
output: ${OUTPUT_MODE}
mode: ${MODE}
commit_msg: ${COMMIT_MSG}
publish_head: ${PUBLISH_HEAD}
timestamp: ${SYNC_TIMESTAMP}"

    cd "$INTERNAL_REPO"

    if [[ "$FIRST_DELIVERY" == "true" ]]; then
      PARTY_INIT_TAG="replica/${PARTY}/init-${SYNC_TIMESTAMP}"
      GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
      GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
      git tag -a "$PARTY_INIT_TAG" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"
      ok "Init tag: $PARTY_INIT_TAG -> ${PUBLISH_HEAD:0:8}"
    fi

    GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
    GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
    git tag -a -f "$PARTY_SYNC_TAG" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"

    GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
    GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
    git tag -a "replica/${PARTY}/sync-${SYNC_TIMESTAMP}" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"

    ok "Sync tag advanced: $PARTY_SYNC_TAG -> ${PUBLISH_HEAD:0:8}"
  else
    log "--resend: sync tags not updated"
  fi

  ok "Delivery complete"
  exit 0
fi

# ── push mode: apply to replica ───────────────────────────────
cd "$REPLICA_REPO"

log "Fetching and updating replica..."
git fetch "$REPLICA_REMOTE"
git checkout -f "$REPLICA_BRANCH"
git reset --hard "${REPLICA_REMOTE}/${REPLICA_BRANCH}"

if [[ "$MODE" == "pr" ]]; then
  SYNC_BRANCH="sync/${TIMESTAMP}"
  git checkout -b "$SYNC_BRANCH"
  log "Sync branch: $SYNC_BRANCH"
fi

if [[ "$FIRST_DELIVERY" == "true" ]]; then
  # First delivery: clear working tree and apply via git archive (clean slate).
  # git apply --3way cannot resolve cross-repo base objects, causing false conflicts
  # when the replica already has files (e.g. a GitHub-initialized README).
  log "First delivery: applying via git archive (clean slate)..."
  git rm -rf . --quiet
  git -C "$INTERNAL_REPO" archive "$PUBLISH_HEAD" | tar -x -C .
  copy_bootstrap "."
else
  log "Applying patch..."
  git apply --3way --whitespace=nowarn "$PATCH_FILE" \
    || die "Patch apply failed. Resolve conflicts and re-run."
fi

git add -A

if git diff --cached --quiet; then
  ok "Nothing to commit after staging."
else
  GIT_AUTHOR_NAME="$SYNC_AUTHOR_NAME" \
  GIT_AUTHOR_EMAIL="$SYNC_AUTHOR_EMAIL" \
  GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
  GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
  git commit \
    -m "$COMMIT_MSG" \
    -m "$(generate_deliver_summary)"

  ok "Commit: $(git rev-parse --short HEAD)"
fi

if [[ "$MODE" == "pr" ]]; then
  git push "$REPLICA_REMOTE" "$SYNC_BRANCH"

  # Ensure the "sync" label exists in the replica repo
  gh label list --repo "$REPLICA_GH_REPO" --json name --jq '.[].name' \
    | grep -qx "sync" \
    || gh label create "sync" --repo "$REPLICA_GH_REPO" --color "0075ca" --description "sync delivery from internal"

  PR_URL=$(gh pr create \
    --repo  "$REPLICA_GH_REPO" \
    --title "$COMMIT_MSG" \
    --body  "$(generate_pr_body)" \
    --base  "$REPLICA_BRANCH" \
    --head  "$SYNC_BRANCH")

  # Apply label separately so a label failure does not abort tag advancement
  gh pr edit "$PR_URL" --add-label "sync" --repo "$REPLICA_GH_REPO" \
    || log "Warning: could not add label 'sync' to PR (non-fatal)"

  ok "PR created: $PR_URL"

elif [[ "$MODE" == "direct" ]]; then
  git push "$REPLICA_REMOTE" "$REPLICA_BRANCH"
  ok "Pushed directly to main"
fi

# ── Step 3: Advance sync tags ─────────────────────────────────
cd "$INTERNAL_REPO"

SYNC_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
TAG_MESSAGE="party: ${PARTY}
output: ${OUTPUT_MODE}
mode: ${MODE}
commit_msg: ${COMMIT_MSG}
publish_head: ${PUBLISH_HEAD}
timestamp: ${SYNC_TIMESTAMP}"

# On first delivery, record an immutable init tag for this party
if [[ "$FIRST_DELIVERY" == "true" ]]; then
  PARTY_INIT_TAG="replica/${PARTY}/init-${SYNC_TIMESTAMP}"
  GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
  GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
  git tag -a "$PARTY_INIT_TAG" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"
  ok "Init tag: $PARTY_INIT_TAG -> ${PUBLISH_HEAD:0:8}"
fi

GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
git tag -a -f "$PARTY_SYNC_TAG" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"

GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
git tag -a "replica/${PARTY}/sync-${SYNC_TIMESTAMP}" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"

ok "Sync tag advanced: $PARTY_SYNC_TAG -> ${PUBLISH_HEAD:0:8}"
ok "Delivery complete"
