#!/usr/bin/env bash
# deliver-to-replica.sh
#
# Milestone sync - Phase 2.
# Delivers the publish/<party> branch content to the external replica.
# Run after: stage-publish.sh -> GHE PR review -> merge.
#
# Usage:
#   # Push as a PR (default)
#   ./scripts/deliver-to-replica.sh --party acme "sync: 2024-Q1"
#
#   # Push directly to main
#   ./scripts/deliver-to-replica.sh --party acme --mode direct "sync: 2024-Q1"
#
#   # Output patch set (3rd party opens a PR — default)
#   ./scripts/deliver-to-replica.sh --party acme --output patch "sync: 2024-Q1"
#
#   # Output patch set (3rd party applies directly to main)
#   ./scripts/deliver-to-replica.sh --party acme --output patch --mode direct "sync: 2024-Q1"
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/../config/sync.conf"

[[ -f "$CONFIG_FILE" ]] || {
  echo "Config file not found: $CONFIG_FILE"
  exit 1
}
# shellcheck source=../config/sync.conf.example
source "$CONFIG_FILE"

# Defaults for optional config values (prevents -u errors when unset)
: "${PUBLISH_BRANCH_PREFIX:=publish}"
: "${PATCH_OUTPUT_DIR:=./sync-patches}"

log() { echo -e "\033[1;34m[deliver]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[  ok   ]\033[0m $*"; }
die() { echo -e "\033[1;31m[ err   ]\033[0m $*" >&2; exit 1; }

# ── Argument parsing ───────────────────────────────────────────
OUTPUT_MODE="push"   # push | patch
MODE="pr"            # pr | direct
PARTY=""
COMMIT_MSG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT_MODE="$2"; shift 2 ;;
    --mode)   MODE="$2";        shift 2 ;;
    --party)  PARTY="$2";       shift 2 ;;
    --*)      die "Unknown option: $1" ;;
    *)        COMMIT_MSG="$1"; shift ;;
  esac
done

[[ -n "$PARTY" ]] || die "Specify a party name with --party\n  Example: $0 --party acme \"sync: 2024-Q1\""
COMMIT_MSG="${COMMIT_MSG:-"sync: $(date +%Y-%m-%d)"}"

case "$OUTPUT_MODE" in
  push|patch) ;;
  *) die "--output must be push or patch" ;;
esac

case "$MODE" in
  pr|direct) ;;
  *) die "--mode must be pr or direct" ;;
esac

PUBLISH_BRANCH="${PUBLISH_BRANCH_PREFIX}/${PARTY}"
PARTY_SYNC_TAG="replica/${PARTY}/last-sync"

log "Party         : $PARTY"
log "Output mode   : $OUTPUT_MODE"
log "Apply mode    : $MODE"
log "Commit message: $COMMIT_MSG"

# ── Helpers ────────────────────────────────────────────────────

# List publish/<party> commits since last-sync
generate_deliver_summary() {
  cd "$INTERNAL_REPO"
  git log --oneline --no-merges "${PARTY_SYNC_TAG}..${PUBLISH_HEAD}" \
    | head -50
}

generate_pr_body() {
  cat << EOF
## ${COMMIT_MSG}

| Field    | Value |
|----------|-------|
| Range    | \`${LAST_SYNC_SHA:0:8}\`..\`${PUBLISH_HEAD:0:8}\` |
| Delivered| $(date '+%Y-%m-%d %H:%M:%S') |

## Change summary

\`\`\`
$(generate_deliver_summary)
\`\`\`

> This PR was auto-generated by the internal sync bot.
> Please review and merge.
EOF
}

# Generate apply.sh — a standalone script for the 3rd party to apply the patch
generate_apply_sh() {
  local output_file="$1"
  local ts="$TIMESTAMP"
  local msg="$COMMIT_MSG"
  local default_mode="$MODE"
  local script_name="sync-${ts}-apply.sh"

  sed \
    -e "s|%%TIMESTAMP%%|${ts}|g" \
    -e "s|%%COMMIT_MSG%%|${msg}|g" \
    -e "s|%%DEFAULT_MODE%%|${default_mode}|g" \
    -e "s|%%SCRIPT_NAME%%|${script_name}|g" \
    << 'APPLY_TEMPLATE' > "$output_file"
#!/usr/bin/env bash
# Sync apply script (generated: %%TIMESTAMP%%)
# Sync message: %%COMMIT_MSG%%
#
# Usage:
#   # Apply with the default mode (%%DEFAULT_MODE%%)
#   ./%%SCRIPT_NAME%%
#
#   # Specify a mode explicitly
#   ./%%SCRIPT_NAME%% --mode pr      # push sync branch and open a PR
#   ./%%SCRIPT_NAME%% --mode direct  # apply directly to main
#
# Prerequisites:
#   - Run from the root of the replica repository
#   - jq must be installed; gh CLI is required only for pr mode
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PATCH_FILE="${SCRIPT_DIR}/sync-%%TIMESTAMP%%.patch"
META_FILE="${SCRIPT_DIR}/sync-%%TIMESTAMP%%-meta.json"
SYNC_BRANCH="sync/%%TIMESTAMP%%"
REPLICA_BRANCH="main"
DEFAULT_MODE="%%DEFAULT_MODE%%"

log() { echo -e "\033[1;34m[apply]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[  ok  ]\033[0m $*"; }
die() { echo -e "\033[1;31m[ err  ]\033[0m $*" >&2; exit 1; }

MODE="${DEFAULT_MODE}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --*)    die "Unknown option: $1" ;;
    *) break ;;
  esac
done

[[ -f "$PATCH_FILE" ]] || die "Patch file not found: $PATCH_FILE"
[[ -f "$META_FILE"  ]] || die "Meta file not found: $META_FILE"
command -v jq >/dev/null 2>&1 || die "jq is not installed"
[[ "$MODE" == "pr" ]] && { command -v gh >/dev/null 2>&1 || die "gh CLI is not installed"; }

PR_TITLE=$(jq -r '.pr_title' "$META_FILE")
PR_BODY=$(jq  -r '.pr_body'  "$META_FILE")

log "Apply mode: $MODE"

if [[ "$MODE" == "pr" ]]; then
  log "Creating branch: $SYNC_BRANCH"
  git checkout -b "$SYNC_BRANCH"

  log "Applying patch..."
  git apply --3way --whitespace=nowarn "$PATCH_FILE" \
    || die "Patch apply failed. Resolve conflicts and re-run."

  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "$PR_TITLE"
    ok "Commit: $(git rev-parse --short HEAD)"
  else
    ok "No changes to commit."
  fi

  git push origin "$SYNC_BRANCH"

  gh pr create \
    --title "$PR_TITLE" \
    --body  "$PR_BODY"  \
    --base  "$REPLICA_BRANCH" \
    --head  "$SYNC_BRANCH"

  ok "PR created"

elif [[ "$MODE" == "direct" ]]; then
  log "Applying directly to main..."
  git checkout "$REPLICA_BRANCH"

  log "Applying patch..."
  git apply --3way --whitespace=nowarn "$PATCH_FILE" \
    || die "Patch apply failed. Resolve conflicts and re-run."

  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "$PR_TITLE"
    ok "Commit: $(git rev-parse --short HEAD)"
  else
    ok "No changes to commit."
  fi

  git push origin "$REPLICA_BRANCH"
  ok "Applied directly to main"

else
  die "--mode must be pr or direct"
fi
APPLY_TEMPLATE
  chmod +x "$output_file"
}

# ── Step 1: Pre-flight checks ─────────────────────────────────
cd "$INTERNAL_REPO"

git rev-parse --verify "refs/heads/${PUBLISH_BRANCH}" >/dev/null 2>&1 \
  || die "Publish branch '$PUBLISH_BRANCH' not found.\n" \
         "Run initial setup first:\n" \
         "  ./scripts/init-replica.sh --party ${PARTY} <start-tag>"

git rev-parse --verify "$PARTY_SYNC_TAG" >/dev/null 2>&1 \
  || die "Sync tag '$PARTY_SYNC_TAG' not found.\n" \
         "Run initial setup first:\n" \
         "  ./scripts/init-replica.sh --party ${PARTY} <start-tag>"

PUBLISH_HEAD=$(git rev-parse "$PUBLISH_BRANCH")
LAST_SYNC_SHA=$(git rev-parse "$PARTY_SYNC_TAG")

if [[ "$PUBLISH_HEAD" == "$LAST_SYNC_SHA" ]]; then
  ok "Already delivered. No undelivered changes on publish branch."
  exit 0
fi

log "Delivery range: ${LAST_SYNC_SHA:0:8}..${PUBLISH_HEAD:0:8}"

# ── Step 2: Generate diff patch ───────────────────────────────
# publish/<party> already has EXCLUDE_PATHS applied by stage-publish.sh
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PATCH_FILE=$(mktemp /tmp/deliver-XXXXXX.patch)
trap 'rm -f "$PATCH_FILE"' EXIT

git diff "${PARTY_SYNC_TAG}..${PUBLISH_BRANCH}" > "$PATCH_FILE"

if [[ ! -s "$PATCH_FILE" ]]; then
  ok "No diff. Skipping."
  exit 0
fi

log "Patch size: $(wc -l < "$PATCH_FILE") lines"

# ── patch mode: write files and exit ──────────────────────────
if [[ "$OUTPUT_MODE" == "patch" ]]; then
  mkdir -p "$PATCH_OUTPUT_DIR"

  DEST_PATCH="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}.patch"
  DEST_META="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}-meta.json"
  DEST_SUMMARY="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}-summary.txt"
  DEST_APPLY="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}-apply.sh"

  cp "$PATCH_FILE" "$DEST_PATCH"

  PR_BODY_VAL="$(generate_pr_body)"

  cat > "$DEST_META" << EOF
{
  "commit_msg":     "${COMMIT_MSG}",
  "publish_head":   "${PUBLISH_HEAD}",
  "last_sync_sha":  "${LAST_SYNC_SHA}",
  "timestamp":      "${TIMESTAMP}",
  "party":          "${PARTY}",
  "sync_branch":    "sync/${TIMESTAMP}",
  "pr_title":       "${COMMIT_MSG}",
  "pr_body":        $(echo "$PR_BODY_VAL" | jq -Rs .),
  "default_mode":   "${MODE}"
}
EOF

  generate_deliver_summary > "$DEST_SUMMARY"
  generate_apply_sh "$DEST_APPLY"

  ok "Patch set generated:"
  echo "  patch   : $DEST_PATCH"
  echo "  meta    : $DEST_META"
  echo "  summary : $DEST_SUMMARY"
  echo "  apply   : $DEST_APPLY"
  echo ""
  echo "Send the following files to the 3rd party:"
  echo "  $DEST_PATCH"
  echo "  $DEST_META"
  echo "  $DEST_APPLY"
  echo ""
  echo "After confirming the replica is updated, advance the sync tag:"
  echo "  cd $INTERNAL_REPO && git tag -a -f $PARTY_SYNC_TAG $PUBLISH_HEAD -m \"delivered: ${TIMESTAMP}\""
  exit 0
fi

# ── push mode: apply to replica ───────────────────────────────
cd "$REPLICA_REPO"

log "Fetching and updating replica..."
git fetch "$REPLICA_REMOTE"
git checkout "$REPLICA_BRANCH"
git merge --ff-only "${REPLICA_REMOTE}/${REPLICA_BRANCH}"

if [[ "$MODE" == "pr" ]]; then
  SYNC_BRANCH="sync/${TIMESTAMP}"
  git checkout -b "$SYNC_BRANCH"
  log "Sync branch: $SYNC_BRANCH"
fi

log "Applying patch..."
git apply --3way --whitespace=nowarn "$PATCH_FILE" \
  || die "Patch apply failed. Resolve conflicts and re-run."

git add -A

if git diff --cached --quiet; then
  ok "Nothing to commit after staging."
else
  GIT_AUTHOR_NAME="$SYNC_AUTHOR_NAME" \
  GIT_AUTHOR_EMAIL="$SYNC_AUTHOR_EMAIL" \
  GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
  GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
  git commit \
    -m "$COMMIT_MSG" \
    -m "$(generate_deliver_summary)"

  ok "Commit: $(git rev-parse --short HEAD)"
fi

if [[ "$MODE" == "pr" ]]; then
  git push "$REPLICA_REMOTE" "$SYNC_BRANCH"

  gh pr create \
    --repo  "$REPLICA_GH_REPO" \
    --title "$COMMIT_MSG" \
    --body  "$(generate_pr_body)" \
    --base  "$REPLICA_BRANCH" \
    --head  "$SYNC_BRANCH" \
    --label "sync"

  ok "PR created"

elif [[ "$MODE" == "direct" ]]; then
  git push "$REPLICA_REMOTE" "$REPLICA_BRANCH"
  ok "Pushed directly to main"
fi

# ── Step 3: Advance sync tag ──────────────────────────────────
cd "$INTERNAL_REPO"

SYNC_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
TAG_MESSAGE="party: ${PARTY}
output: ${OUTPUT_MODE}
mode: ${MODE}
commit_msg: ${COMMIT_MSG}
publish_head: ${PUBLISH_HEAD}
timestamp: ${SYNC_TIMESTAMP}"

GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
git tag -a -f "$PARTY_SYNC_TAG" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"

GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
git tag -a "replica/${PARTY}/sync-${SYNC_TIMESTAMP}" "$PUBLISH_HEAD" -m "$TAG_MESSAGE"

ok "Sync tag advanced: $PARTY_SYNC_TAG -> ${PUBLISH_HEAD:0:8}"
ok "Delivery complete"
