#!/usr/bin/env bash
# sync-to-replica.sh
#
# Milestone sync script (legacy — kept for backward compatibility).
# Squashes changes since the last-sync tag and delivers them to the replica.
# For new workflows, use stage-publish.sh + deliver-to-replica.sh instead.
#
# Usage:
#   # Push as a PR (default)
#   ./scripts/sync-to-replica.sh --party acme "sync: 2024-Q1"
#
#   # Push directly to main
#   ./scripts/sync-to-replica.sh --party acme --mode direct "sync: 2024-Q1"
#
#   # Output patch set (3rd party opens a PR — default)
#   ./scripts/sync-to-replica.sh --party acme --output patch "sync: 2024-Q1"
#
#   # Output patch set (3rd party applies directly to main)
#   ./scripts/sync-to-replica.sh --party acme --output patch --mode direct "sync: 2024-Q1"
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/../config/sync.conf"

[[ -f "$CONFIG_FILE" ]] || {
  echo "Config file not found: $CONFIG_FILE"
  exit 1
}
# shellcheck source=../config/sync.conf.example
source "$CONFIG_FILE"

# Defaults for optional config values (prevents -u errors when unset)
declare -p EXCLUDE_PATHS >/dev/null 2>&1 || EXCLUDE_PATHS=()
: "${PATCH_OUTPUT_DIR:=./sync-patches}"

log() { echo -e "\033[1;34m[sync]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[  ok ]\033[0m $*"; }
die() { echo -e "\033[1;31m[ err ]\033[0m $*" >&2; exit 1; }

# ── Argument parsing ───────────────────────────────────────────
OUTPUT_MODE="push"   # push | patch
MODE="pr"            # pr | direct
PARTY=""
COMMIT_MSG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT_MODE="$2"; shift 2 ;;
    --mode)   MODE="$2";        shift 2 ;;
    --party)  PARTY="$2";       shift 2 ;;
    --*)      die "Unknown option: $1" ;;
    *)        COMMIT_MSG="$1"; shift ;;
  esac
done

[[ -n "$PARTY" ]] || die "Specify a party name with --party\n  Example: $0 --party acme \"sync: 2024-Q1\""

COMMIT_MSG="${COMMIT_MSG:-"sync: $(date +%Y-%m-%d)"}"

case "$OUTPUT_MODE" in
  push|patch) ;;
  *) die "--output must be push or patch" ;;
esac

case "$MODE" in
  pr|direct) ;;
  *) die "--mode must be pr or direct" ;;
esac

# Load per-party config (provides REPLICA_REPO, REPLICA_REMOTE, REPLICA_BRANCH, REPLICA_GH_REPO)
PARTY_CONFIG="${SCRIPT_DIR}/../config/party/${PARTY}.conf"
[[ -f "$PARTY_CONFIG" ]] || die "Party config not found: $PARTY_CONFIG\n  Run: cp config/party/party.conf.example config/party/${PARTY}.conf and edit it"
# shellcheck source=../config/party/party.conf.example
source "$PARTY_CONFIG"

# Party-scoped sync tag
PARTY_SYNC_TAG="replica/${PARTY}/last-sync"

log "Party         : $PARTY"
log "Output mode   : $OUTPUT_MODE"
log "Apply mode    : $MODE"
log "Commit message: $COMMIT_MSG"

# ── Helpers ────────────────────────────────────────────────────
build_exclude_args() {
  EXCLUDE_ARGS=()
  for path in ${EXCLUDE_PATHS[@]+"${EXCLUDE_PATHS[@]}"}; do
    EXCLUDE_ARGS+=(":!${path}")
  done
}

generate_sync_summary() {
  cd "$INTERNAL_REPO"
  git log --oneline --no-merges "${PARTY_SYNC_TAG}..${INTERNAL_HEAD}" \
    -- . ${EXCLUDE_ARGS[@]+"${EXCLUDE_ARGS[@]}"} \
    | head -50
}

generate_pr_body() {
  cat << EOF
## ${COMMIT_MSG}

| Field    | Value |
|----------|-------|
| Range    | \`${SYNC_BASE:0:8}\`..\`${INTERNAL_HEAD:0:8}\` |
| Synced at| $(date '+%Y-%m-%d %H:%M:%S') |

## Change summary

\`\`\`
$(generate_sync_summary)
\`\`\`

> This PR was auto-generated by the internal sync bot.
> Please review and merge.
EOF
}

# Generate apply.sh — a standalone script for the 3rd party to apply the patch.
# %%PLACEHOLDER%% tokens are replaced by sed at generation time.
# Literal $ inside the heredoc must be escaped as \$ (unquoted heredoc).
generate_apply_sh() {
  local output_file="$1"
  local ts="$TIMESTAMP"
  local msg="$COMMIT_MSG"
  local default_mode="$MODE"
  local script_name="sync-${ts}-apply.sh"

  sed \
    -e "s|%%TIMESTAMP%%|${ts}|g" \
    -e "s|%%COMMIT_MSG%%|${msg}|g" \
    -e "s|%%DEFAULT_MODE%%|${default_mode}|g" \
    -e "s|%%SCRIPT_NAME%%|${script_name}|g" \
    << 'APPLY_TEMPLATE' > "$output_file"
#!/usr/bin/env bash
# Sync apply script (generated: %%TIMESTAMP%%)
# Sync message: %%COMMIT_MSG%%
#
# Usage:
#   # Apply with the default mode (%%DEFAULT_MODE%%)
#   ./%%SCRIPT_NAME%%
#
#   # Specify a mode explicitly
#   ./%%SCRIPT_NAME%% --mode pr      # push sync branch and open a PR
#   ./%%SCRIPT_NAME%% --mode direct  # apply directly to main
#
# Prerequisites:
#   - Run from the root of the replica repository
#   - jq must be installed; gh CLI is required only for pr mode
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PATCH_FILE="${SCRIPT_DIR}/sync-%%TIMESTAMP%%.patch"
META_FILE="${SCRIPT_DIR}/sync-%%TIMESTAMP%%-meta.json"
SYNC_BRANCH="sync/%%TIMESTAMP%%"
REPLICA_BRANCH="main"
DEFAULT_MODE="%%DEFAULT_MODE%%"

log() { echo -e "\033[1;34m[apply]\033[0m $*"; }
ok()  { echo -e "\033[1;32m[  ok ]\033[0m $*"; }
die() { echo -e "\033[1;31m[ err ]\033[0m $*" >&2; exit 1; }

MODE="${DEFAULT_MODE}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --*)    die "Unknown option: $1" ;;
    *) break ;;
  esac
done

[[ -f "$PATCH_FILE" ]] || die "Patch file not found: $PATCH_FILE"
[[ -f "$META_FILE"  ]] || die "Meta file not found: $META_FILE"
command -v jq >/dev/null 2>&1 || die "jq is not installed"
[[ "$MODE" == "pr" ]] && { command -v gh >/dev/null 2>&1 || die "gh CLI is not installed"; }

PR_TITLE=$(jq -r '.pr_title' "$META_FILE")
PR_BODY=$(jq  -r '.pr_body'  "$META_FILE")

log "Apply mode: $MODE"

if [[ "$MODE" == "pr" ]]; then
  log "Creating branch: $SYNC_BRANCH"
  git checkout -b "$SYNC_BRANCH"

  log "Applying patch..."
  git apply --3way --whitespace=nowarn "$PATCH_FILE" \
    || die "Patch apply failed. Resolve conflicts and re-run."

  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "$PR_TITLE"
    ok "Commit: $(git rev-parse --short HEAD)"
  else
    ok "No changes to commit."
  fi

  git push origin "$SYNC_BRANCH"

  gh pr create \
    --title "$PR_TITLE" \
    --body  "$PR_BODY"  \
    --base  "$REPLICA_BRANCH" \
    --head  "$SYNC_BRANCH"

  ok "PR created"

elif [[ "$MODE" == "direct" ]]; then
  log "Applying directly to main..."
  git checkout "$REPLICA_BRANCH"

  log "Applying patch..."
  git apply --3way --whitespace=nowarn "$PATCH_FILE" \
    || die "Patch apply failed. Resolve conflicts and re-run."

  git add -A
  if ! git diff --cached --quiet; then
    git commit -m "$PR_TITLE"
    ok "Commit: $(git rev-parse --short HEAD)"
  else
    ok "No changes to commit."
  fi

  git push origin "$REPLICA_BRANCH"
  ok "Applied directly to main"

else
  die "--mode must be pr or direct"
fi
APPLY_TEMPLATE
  chmod +x "$output_file"
}

# ── Step 1: Verify last-sync tag ──────────────────────────────
cd "$INTERNAL_REPO"
build_exclude_args

git rev-parse --verify "$PARTY_SYNC_TAG" >/dev/null 2>&1 \
  || die "Sync tag '$PARTY_SYNC_TAG' not found.\n" \
         "Run initial setup first:\n" \
         "  ./scripts/init-replica.sh --party ${PARTY} <start-tag>"

SYNC_BASE=$(git rev-parse "$PARTY_SYNC_TAG")
INTERNAL_HEAD=$(git rev-parse HEAD)

if [[ "$SYNC_BASE" == "$INTERNAL_HEAD" ]]; then
  ok "Already in sync. No diff."
  exit 0
fi

log "Sync range: ${SYNC_BASE:0:8}..${INTERNAL_HEAD:0:8}"

# ── Step 2: Generate diff patch ───────────────────────────────
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PATCH_FILE=$(mktemp /tmp/replica-sync-XXXXXX.patch)
trap 'rm -f "$PATCH_FILE"' EXIT

git diff "${PARTY_SYNC_TAG}..HEAD" -- . ${EXCLUDE_ARGS[@]+"${EXCLUDE_ARGS[@]}"} > "$PATCH_FILE"

if [[ ! -s "$PATCH_FILE" ]]; then
  ok "No diff after applying exclude paths. Skipping."
  exit 0
fi

log "Patch size: $(wc -l < "$PATCH_FILE") lines"

# ── patch mode: write files and exit ──────────────────────────
if [[ "$OUTPUT_MODE" == "patch" ]]; then
  mkdir -p "$PATCH_OUTPUT_DIR"

  DEST_PATCH="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}.patch"
  DEST_META="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}-meta.json"
  DEST_SUMMARY="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}-summary.txt"
  DEST_APPLY="${PATCH_OUTPUT_DIR}/sync-${TIMESTAMP}-apply.sh"

  cp "$PATCH_FILE" "$DEST_PATCH"

  PR_BODY="$(generate_pr_body)"

  cat > "$DEST_META" << EOF
{
  "commit_msg":    "${COMMIT_MSG}",
  "sync_base":     "${SYNC_BASE}",
  "internal_head": "${INTERNAL_HEAD}",
  "timestamp":     "${TIMESTAMP}",
  "party":         "${PARTY}",
  "sync_branch":   "sync/${TIMESTAMP}",
  "pr_title":      "${COMMIT_MSG}",
  "pr_body":       $(echo "$PR_BODY" | jq -Rs .),
  "default_mode":  "${MODE}",
  "exclude_paths": $(printf '%s\n' ${EXCLUDE_PATHS[@]+"${EXCLUDE_PATHS[@]}"} | jq -R . | jq -s .)
}
EOF

  generate_sync_summary > "$DEST_SUMMARY"
  generate_apply_sh "$DEST_APPLY"

  ok "Patch set generated:"
  echo "  patch   : $DEST_PATCH"
  echo "  meta    : $DEST_META"
  echo "  summary : $DEST_SUMMARY"
  echo "  apply   : $DEST_APPLY"
  echo ""
  echo "Send the following files to the 3rd party:"
  echo "  $DEST_PATCH"
  echo "  $DEST_META"
  echo "  $DEST_APPLY"
  echo ""
  echo "After confirming the replica is updated, advance the sync tag:"
  echo "  cd $INTERNAL_REPO && git tag -f $PARTY_SYNC_TAG $INTERNAL_HEAD"
  exit 0
fi

# ── push mode: apply to replica ───────────────────────────────
cd "$REPLICA_REPO"

log "Fetching and updating replica..."
git fetch "$REPLICA_REMOTE"
git checkout "$REPLICA_BRANCH"
git merge --ff-only "${REPLICA_REMOTE}/${REPLICA_BRANCH}"

if [[ "$MODE" == "pr" ]]; then
  SYNC_BRANCH="sync/${TIMESTAMP}"
  git checkout -b "$SYNC_BRANCH"
  log "Sync branch: $SYNC_BRANCH"
fi

log "Applying patch..."
git apply --3way --whitespace=nowarn "$PATCH_FILE" \
  || die "Patch apply failed. Resolve conflicts and re-run."

git add -A

if git diff --cached --quiet; then
  ok "Nothing to commit after staging."
else
  GIT_AUTHOR_NAME="$SYNC_AUTHOR_NAME" \
  GIT_AUTHOR_EMAIL="$SYNC_AUTHOR_EMAIL" \
  GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
  GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
  git commit \
    -m "$COMMIT_MSG" \
    -m "$(generate_sync_summary)"

  ok "Commit: $(git rev-parse --short HEAD)"
fi

if [[ "$MODE" == "pr" ]]; then
  git push "$REPLICA_REMOTE" "$SYNC_BRANCH"

  gh pr create \
    --repo  "$REPLICA_GH_REPO" \
    --title "$COMMIT_MSG" \
    --body  "$(generate_pr_body)" \
    --base  "$REPLICA_BRANCH" \
    --head  "$SYNC_BRANCH" \
    --label "sync"

  ok "PR created"

elif [[ "$MODE" == "direct" ]]; then
  git push "$REPLICA_REMOTE" "$REPLICA_BRANCH"
  ok "Pushed directly to main"
fi

# ── Step 6: Advance sync tag ──────────────────────────────────
cd "$INTERNAL_REPO"

SYNC_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
TAG_MESSAGE="party: ${PARTY}
output: ${OUTPUT_MODE}
mode: ${MODE}
commit_msg: ${COMMIT_MSG}
timestamp: ${SYNC_TIMESTAMP}"

GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
git tag -a -f "$PARTY_SYNC_TAG" "$INTERNAL_HEAD" -m "$TAG_MESSAGE"

GIT_COMMITTER_NAME="$SYNC_AUTHOR_NAME" \
GIT_COMMITTER_EMAIL="$SYNC_AUTHOR_EMAIL" \
git tag -a "replica/${PARTY}/sync-${SYNC_TIMESTAMP}" "$INTERNAL_HEAD" -m "$TAG_MESSAGE"

ok "Sync tag advanced: $PARTY_SYNC_TAG -> ${INTERNAL_HEAD:0:8}"
ok "Sync complete"
